---
name: prgate
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python:
          - '3.7'
          - '3.8'
          - '3.9'
#          - '3.10'
#          - '3.11'
        etcd:
          - 'v3.0.17'
          - 'v3.1.20'
          - 'v3.2.32'
          - 'v3.3.10'
          - 'v3.3.27'
          - 'v3.4.22'
          - 'v3.5.6'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install python dependencies
        run: pip install poetry==1.2.2

      - name: Cache virtualenv dependencies across builds
        uses: actions/cache@v3
        with:
          path: |
            .venv
          key: ${{ github.repository }}-${{ runner.os }}-${{ matrix.python }}-venv-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ github.repository }}-${{ runner.os }}-${{ matrix.python }}-venv-

      - name: Cache etcd across builds
        uses: actions/cache@v3
        with:
          path: |
            .etcd
          key: ${{ github.repository }}-${{ runner.os }}-etcd-${{ matrix.etcd }}
          restore-keys: |
            ${{ github.repository }}-${{ runner.os }}-etcd-${{ matrix.etcd }}

      - name: Install dependencies
        run: make install

      - name: Lint code
        run: make lint

      - name: Run tests
        run: make test
        env:
          TEST_ETCD_VERSION: ${{ matrix.etcd }}
